INSERT INTO animals (name, cuteness, species, location) VALUES
    ('Boris',798,'dog','Luxembourg'),
    ('Rose of Sharon',1,'chicken','Lawn'),
    ('Damian',5,'roly_poly','Backyard dirt'),
    ('Her Majesty',10,'rat','Subway station, staring at me'),
    ('James',789,'howler_monkey','Kapok tree in Ecuador'),
    ('roger rabbit',0,'horrible_rabbit','an office'),
    ('jeff',3,'human','jeff’s apartment'),
    ('Kiva',1000,'cat','Charlie''s computer chair'),
    ('eevee',3,'komodo_dragon','australia'),
    ('Raven',800,'cat','the couch'),
    ('Eno',0,'cat','the Third Circle of Hell, where gluttons are punished for their sins'),
    ('Bronson',999,'dog','in all of our hearts'),
    ('Kermit',700,'frog','Rainbow Connection'),
    ('Dumbo',90,'elephant','Circus'),
    ('Zeus',10,'dog','neverland'),
    ('Leo',10,'cat','chicago'),
    ('Sam',1000,'dog','Houston'),
    ('Krown',999,'dog','Island of Youth'),
    ('Red-lipped batfish',0,'fish','Galápagos Island'),
    ('Blobfish',0,'fish','Australia'),
    ('Aye-Aye',0,'monkey','Madagascar'),
    ('Toby',1000,'dog','The balcony'),
    ('Rigby',11,'racoon','the park'),
    ('Eileen',89,'mole','a coffee shop'),
    ('Appa',200,'sky_bison','Eastern Air Temple'),
    ('Momo',800,'winged_lemur','Eastern Air Temple'),
    ('Funbeak',1,'not_a_terrifying_robot_chicken','Definitely not right behind you'),
    ('Lawl',475,'hyena','Lusaka'),
    ('Polly',732,'parrot','library'),
    ('Slink',999,'ferret','cupboard'),
    ('Rascal',729,'raccoon','dumpster'),
    ('Aiden',867,'seahorse','12 Coral St'),
    ('Scabby',412,'rat','Union HQ'),
    ('Batman',932,'robin','Reservoir'),
    ('Stabbers',583,'urchin','Maine'),
    ('Hoppin',987,'rabbit','cabbage patch'),
    ('Flopsy',872,'rabbit','carrot patch'),
    ('Mopsy',924,'rabbit','radishes'),
    ('Cottontail',978,'rabbit','spinach plot'),
    ('Trogdor',1000,'dragon','Free Country, USA'),
    ('Dutch',483,'mouse','amsterdam'),
    ('Fetch',999,'dog','backyard'),
    ('Queen',759,'lion','Ariaal Region'),
    ('Sri',555,'mongoose','Delhi'),
    ('Snowball',986,'leopard','Nepal'),
    ('Harry',243,'python','Brazil'),
    ('Bolt',34,'eel','P. Sherman Wallaby Way'),
    ('Stacy',999,'cat','chicago'),
    ('CJ',100,'dog','The white house'),
    ('Finn',900,'dog','Siberia'),
    ('Baby Meow Meow',500,'cat','Dallas TX'),
    ('Molly',750,'cat','Garland, TX'),
    ('Minnie',699,'cat','Texas'),
    ('Clifford',300,'big_red_dog','Afghanistan'),
    ('Babar',50,'elephant','France'),
    ('Jiminy',5,'cricket','New York City'),
    ('reggie',1000,'owlbear','forgotten realm'),
    ('Bash',8,'dog','El Paso'),
    ('Kitty',8,'cat','El Paso'),
    ('Apple',999,'dog','El Paso'),
    ('Peanut Butter',900,'cat','Chelsea'),
    ('Arthur',55,'aardvark','where ants live'),
    ('Reginald',100,'rat','rat home'),
    ('Patrocles',85,'parrot','jungle'),
    ('Shark',10,'shark','Ocean'),
    ('August',7,'cat','on a pillow'),
    ('Jimothy',3,'skunk','backyard'),
    ('Hot Cheeto Hatred',0,'deer','Wisconsin'),
    ('Wilhemina',10,'chicken','California'),
    ('Girard',500,'chicken','France'),
    ('Peter',179,'rabbit','England'),
    ('Benjamin',568,'bunny','England'),
    ('Juniper',799,'fox','Bahrain'),
    ('Pumpkin',479,'raccoon','Jamaica'),
    ('Mutty',1000,'cat','Brooklyn'),
    ('Archimedes',20,'owl','With Merlin'),
    ('Miguel',800,'snake','Montana'),
    ('Tim',562,'horse','Montana'),
    ('Manny',500,'mantis_shrimp','Sea'),
    ('Lily',500,'dog','Atlanta'),
    ('marty',900,'cat','chicago'),
    ('GODZILLA',10,'kaiju','mariana trench'),
    ('Tiamat',1000,'dragon','Forgotten Realms'),
    ('kangaroo',5,'kangaroo','Australia'),
    ('Perry the Platypus',359,'platypus','9297 Polly Parkway Danville'),
    ('Kinder',900,'dog','Island of Youth'),
    ('Romeo',800,'dog','Hialeah'),
    ('Puti',500,'dog','Miami'),
    ('Chewie',1000,'cat','the cat tree'),
    ('Beau',1000,'cat','the chair'),
    ('Big Moose',1000,'cat','everywhere you look');
